### ISSUE TITLE
null pointer error for JSON type field in addAllTablesUsedInQuery function.

### ISSUE THREAD

**Issue by TunahanOcal** [GoogleCloudPlatform/zetasql-toolkit#17]
Hello everyone,
I am using addAllTablesUsedInQuery function to create a catalog. However, if there is a JSON type column in the table, I am getting null pointer exception.

You can see the exception in the screenshot below:

![Screenshot 2023-08-08 at 15 08 19](https://github.com/GoogleCloudPlatform/zetasql-toolkit/assets/49438832/2e93c309-c455-4c26-ac58-7f94ccd98035)

Thans in advance.

**Comment by ppaglilla** [comment]
Thank you for reporting this!

I found the cause of this bug. I'll address it and release a new version of the toolkit in the next couple of days.

**Comment by goktugkose** [comment]
Hello @ppaglilla,

Same issue persists with the function `addAllFunctionsUsedInQuery` when a BigQuery function holds a return type of JSON type. Since you plan to patch a similar bug, I want to contribute by revealing another unexpected behavior.

Thank you for your support 🙏

**Comment by ppaglilla** [comment]
Thanks for bringing the functions case up as well!

It is caused by the same problem as the tables one, so they'll be resolved together.

**Comment by ppaglilla** [comment]
Fixed in release `0.4.1`. Thank you for reporting and apologies for the delayed release!
