### ISSUE TITLE
Analyzing Queries Without Catalog Validations

### ISSUE THREAD

**Issue by SDorgan** [GoogleCloudPlatform/zetasql-toolkit#18]
I’m having troubles with the usage of the analyzer in the AnalyzeWithoutCatlog example. If I try to validate the following queries by themselves:
`SELECT column from t;` or `UPDATE t SET column1 = '';`

The client will always answers with:
`INVALID_ARGUMENT: Table not found: t`

I’m looking into analyzing queries and accessing their syntax tree without any Catalog Validation. Is there a way to achieve this with the current toolkit?

**Comment by SDorgan** [comment]
Sorry for the late response. I think the Parser with the `parseScript` function might be what I was looking for actually. I'll look into the `ParseTreeVisitor` as well. Thanks once again 😄

**Comment by ppaglilla** [comment]
You're welcome! Thank you for the question!
