### ISSUE TITLE
ZetaSQL supports Mac M1 and M2 chips

### ISSUE THREAD

**Issue by emincanoguz11** [GoogleCloudPlatform/zetasql-toolkit#26]
Hi there,

I have a Mac M1 Pro but I get an error in ZetaSQL because of unsupported OS. Can we solve this problem? Because we want to debug and add new features but in this case we are struggling. 

Best regards,
Emin

**Comment by ppaglilla** [comment]
Hi Emin!

I _think_ ZetaSQL works on arm Macs if you run an x86_64 JVM through Rosetta.  Native arm builds are unfortunately not supported by ZetaSQL, at least at the time or writing.

I recommend installing Rosetta and an x86 JDK, then giving it a try. I don't have an arm Mac to test it myself and confirm it however.

**Comment by emincanoguz11** [comment]
Hi Pablo,

Thanks for the advice.  I want to debug code and I don't want to use Docker for that reason. This is my company PC and I don't install Rosetta for this reason.

Unfortunately this is the main problem with Zeta. 

Anyway, maybe I will buy a VM for this reason and check the code.

Best regards,
Emin
