### ISSUE TITLE
Valid dataset id is flagged as invalid due to incorrect regex pattern

### ISSUE THREAD

**Issue by dion-ricky** [GoogleCloudPlatform/zetasql-toolkit#68]
During parsing I got an invalid BigQuery reference error, after looking at the code I realized that this regex pattern is the reason:
https://github.com/GoogleCloudPlatform/zetasql-toolkit/blob/d31b44cb0f45f73f20c52deaba87cae79e399fdf/zetasql-toolkit-bigquery/src/main/java/com/google/zetasql/toolkit/catalog/bigquery/BigQueryReference.java#L33

BigQuery dataset name can contain any letters, numbers, and underscores, https://cloud.google.com/bigquery/docs/datasets#dataset-naming.

**Comment by ppaglilla** [comment]
Reviewing the PR!

**Comment by dion-ricky** [comment]
I have opened new PR #72. Please check, thanks

**Comment by ppaglilla** [comment]
Merged for version `0.5.3`
